#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClpQrColoring.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ClpQrColoring")]
	public partial class ColorAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public ColorAppDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ClpQrColoringConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ColorAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ColorAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ColorAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ColorAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _CreateDT;
		
		private string _AwsS3OrigImgKey;
		
		private string _AwsS3WarpedImgKey;
		
		private string _AwsS3VideoKey;
		
		private string _AwsS3BucketDomain;
		
		private System.Nullable<int> _WarpImageErrorCode;
		
		private System.Nullable<bool> _IsVideoCreated;
		
		private string _AwsS3VideoThumbnailKey;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCreateDTChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDTChanged();
    partial void OnAwsS3OrigImgKeyChanging(string value);
    partial void OnAwsS3OrigImgKeyChanged();
    partial void OnAwsS3WarpedImgKeyChanging(string value);
    partial void OnAwsS3WarpedImgKeyChanged();
    partial void OnAwsS3VideoKeyChanging(string value);
    partial void OnAwsS3VideoKeyChanged();
    partial void OnAwsS3BucketDomainChanging(string value);
    partial void OnAwsS3BucketDomainChanged();
    partial void OnWarpImageErrorCodeChanging(System.Nullable<int> value);
    partial void OnWarpImageErrorCodeChanged();
    partial void OnIsVideoCreatedChanging(System.Nullable<bool> value);
    partial void OnIsVideoCreatedChanged();
    partial void OnAwsS3VideoThumbnailKeyChanging(string value);
    partial void OnAwsS3VideoThumbnailKeyChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Char(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AwsS3OrigImgKey", DbType="VarChar(70)")]
		public string AwsS3OrigImgKey
		{
			get
			{
				return this._AwsS3OrigImgKey;
			}
			set
			{
				if ((this._AwsS3OrigImgKey != value))
				{
					this.OnAwsS3OrigImgKeyChanging(value);
					this.SendPropertyChanging();
					this._AwsS3OrigImgKey = value;
					this.SendPropertyChanged("AwsS3OrigImgKey");
					this.OnAwsS3OrigImgKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AwsS3WarpedImgKey", DbType="VarChar(70)")]
		public string AwsS3WarpedImgKey
		{
			get
			{
				return this._AwsS3WarpedImgKey;
			}
			set
			{
				if ((this._AwsS3WarpedImgKey != value))
				{
					this.OnAwsS3WarpedImgKeyChanging(value);
					this.SendPropertyChanging();
					this._AwsS3WarpedImgKey = value;
					this.SendPropertyChanged("AwsS3WarpedImgKey");
					this.OnAwsS3WarpedImgKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AwsS3VideoKey", DbType="VarChar(70)")]
		public string AwsS3VideoKey
		{
			get
			{
				return this._AwsS3VideoKey;
			}
			set
			{
				if ((this._AwsS3VideoKey != value))
				{
					this.OnAwsS3VideoKeyChanging(value);
					this.SendPropertyChanging();
					this._AwsS3VideoKey = value;
					this.SendPropertyChanged("AwsS3VideoKey");
					this.OnAwsS3VideoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AwsS3BucketDomain", DbType="VarChar(150)")]
		public string AwsS3BucketDomain
		{
			get
			{
				return this._AwsS3BucketDomain;
			}
			set
			{
				if ((this._AwsS3BucketDomain != value))
				{
					this.OnAwsS3BucketDomainChanging(value);
					this.SendPropertyChanging();
					this._AwsS3BucketDomain = value;
					this.SendPropertyChanged("AwsS3BucketDomain");
					this.OnAwsS3BucketDomainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarpImageErrorCode", DbType="Int")]
		public System.Nullable<int> WarpImageErrorCode
		{
			get
			{
				return this._WarpImageErrorCode;
			}
			set
			{
				if ((this._WarpImageErrorCode != value))
				{
					this.OnWarpImageErrorCodeChanging(value);
					this.SendPropertyChanging();
					this._WarpImageErrorCode = value;
					this.SendPropertyChanged("WarpImageErrorCode");
					this.OnWarpImageErrorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVideoCreated", DbType="Bit")]
		public System.Nullable<bool> IsVideoCreated
		{
			get
			{
				return this._IsVideoCreated;
			}
			set
			{
				if ((this._IsVideoCreated != value))
				{
					this.OnIsVideoCreatedChanging(value);
					this.SendPropertyChanging();
					this._IsVideoCreated = value;
					this.SendPropertyChanged("IsVideoCreated");
					this.OnIsVideoCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AwsS3VideoThumbnailKey", DbType="VarChar(70)")]
		public string AwsS3VideoThumbnailKey
		{
			get
			{
				return this._AwsS3VideoThumbnailKey;
			}
			set
			{
				if ((this._AwsS3VideoThumbnailKey != value))
				{
					this.OnAwsS3VideoThumbnailKeyChanging(value);
					this.SendPropertyChanging();
					this._AwsS3VideoThumbnailKey = value;
					this.SendPropertyChanged("AwsS3VideoThumbnailKey");
					this.OnAwsS3VideoThumbnailKeyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
